### ISSUE TITLE
How can I make an integer type field auto-increment?

### ISSUE THREAD

**Issue by Maizer** [VinGarcia/ksql#56] opened 2024-12-02 17:01 UTC
I want to achieve the effect of 

`num = num+1`

but I don't know how to do it.
Thank you.

**Comment by VinGarcia** [comment] 2024-12-02 17:56
Hey @Maizer good afternoon!

So I am assuming you want to use this for an ID on the database correct?

In this example here:

https://github.com/VinGarcia/ksql/blob/master/examples/all_adapters/all_adapters.go

We have a small table definition for each of the supported types of adapters, the dbms tool (i.e. postgres, mysql or sqlserver) is the one responsible for doing the auto-increment, you don't have to do nothing on the KSQL side.

That said KSQL does have some support for this database behavior: The `Insert()` function will automatically retrieve the ID from the table right after it is inserted which is particularly useful for tables whose main ID works with auto-increment:

https://pkg.go.dev/github.com/vingarcia/ksql#DB.Insert

To be clear the expected use for this is like this:

<img width="369" alt="image" src="https://github.com/user-attachments/assets/9239a051-a8fc-440b-afef-fed2d116fcf4">

The `&` means we are sending a reference of the instance to KSQL so KSQL can update the original record after it retrieves the ID.

Also note that the `Insert()` function will use the table definition to know what column or columns it should interpret as ID columns, so make sure that when you call `ksql.NewTable("table_name", "id_column_name")` you pass the right column name there.

**Comment by Maizer** [comment] 2024-12-02 18:18
Thank you. It's midnight here.😄
 I have a field (num) that calculates quantities. If a user clicks, I will increment num by 1, or if the user cancels, I will decrement num by 1. Typically, I would use existing database methods for calculation, such as in MySQL:

update student set score=score+1 where id = 1

I would like to ask if KSQL supports such operations. Thank you very much for your help.
```

**Comment by VinGarcia** [comment] 2024-12-02 18:32
Hey @Maizer, KSQL aims to be very simple and powerful so yeah we don't have that.

You can run the query you shared like this:

```go
result, err := db.Exec(ctx, `update student set score=score+1 where id = 1`)
n, err := result.RowsAffected()
if err != nil {
  // ...
}
if n == 0 {
   return fmt.Errorf("student not found")
}
```

In this case I am forced to return an error on `RowsAffected()`, although I never saw it returning anything but nil, it might still be good to check it just in case.

**Comment by Maizer** [comment] 2024-12-03 00:40
Okay, I will try your method. Thank you.

This method is uncommon, but it is critical because it helps prevent concurrency issues. In concurrent systems, computational errors due to race conditions or synchronization problems can lead to serious and potentially catastrophic consequences.

**Comment by VinGarcia** [comment] 2024-12-03 13:03
I don't even think it is that uncommon, doing operations directly on the database is a common pattern that brings the benefits you mentioned. The thing is that there is no simple way for the KSQL API to provide all the possible types of operations that SQL allows you to implement in a simple way, because SQL is a full language so the only way for KSQL to give you that level of flexibility is to be as complex as SQL or more complex (which is the sin of most if not all ORMs)

So in the end using SQL for this type of operation is considered by many including me the right way of doing it. KSQL was designed to make things you do 90% of the time faster, while still making it possible and uncomplicated to write the other 10% by using SQL.

So I will close this issue for now, but feel free to open a new one at any time =]

**Closed by VinGarcia** 2024-12-03 13:03 UTC
