### ISSUE TITLE
I can't use KSQL with a table without int64 primary key?

### ISSUE THREAD

**Issue by nenodias** [VinGarcia/ksql#52] opened 2024-10-22 21:09 UTC
I have this struct

```
type Socio struct {
	CnpjBasico                     *string    `ksql:"cnpj_basico"`
	IdSocio                        *string    `ksql:"id_socio"`
	Nome                           *string    `ksql:"nome"`
	DocumentoSocio                 *string    `ksql:"documento_socio"`
	Qualificacao                   *int64     `ksql:"qualificacao"`
	DataEntrada                    *time.Time `ksql:"data_entrada"`
	IdPais                         *int64     `ksql:"id_pais"`
	CpfRepresentanteLegal          *string    `ksql:"cpf_representante_legal"`
	NomeRepresentanteLegal         *string    `ksql:"nome_representante_legal"`
	QualificacaoRepresentanteLegal *int64     `ksql:"qualificacao_representante_legal"`
	FaixaEtariaSocio               *string    `ksql:"faixa_etaria_socio"`
}
```
And this table

```
CREATE TABLE `socios` (
  `cnpj_basico` longtext DEFAULT NULL,
  `id_socio` longtext DEFAULT NULL,
  `nome` longtext DEFAULT NULL,
  `documento_socio` longtext DEFAULT NULL,
  `qualificacao` int(11) DEFAULT NULL,
  `data_entrada` date DEFAULT NULL,
  `id_pais` int(11) DEFAULT NULL,
  `cpf_representante_legal` longtext DEFAULT NULL,
  `nome_representante_legal` longtext DEFAULT NULL,
  `qualificacao_representante_legal` int(11) DEFAULT NULL,
  `faixa_etaria_socio` longtext DEFAULT NULL
)
```

I was trying to import some data from CSV into the table of MySQL.
![image](https://github.com/user-attachments/assets/2ae66c62-ad1f-4773-86aa-4ffa4753c6cc)

**Comment by nenodias** [comment] 2024-10-23 11:26
I've tried using Insert method. And filling the fields by reading a csv.
```
var SociosTable = ksql.NewTable("socios")
err = db.Insert(ctx, SociosTable, &Socio{
		CnpjBasico: "96.974.956/0001-63",
                ...//Filling the fields by csv
	})
```

**Comment by VinGarcia** [comment] 2024-10-23 17:02
Hey @nenodias when you define a `ksql.NewTable()` you can pass the ID or list of IDs in case of a composed key as the second argument.

You can omit it if the table id field is simply named `id`, for all other cases you need to specify it like this:

```go
	var SociosTable = ksql.NewTable("socios", "id_socio")
	err = db.Insert(ctx, SociosTable, &Socio{
		CnpjBasico: "96.974.956/0001-63",
                ...//Filling the fields by csv
	})
```

I am still a little puzzled because I would not expect the error you saw if the problema was the configuration of the `ksql.NewTable()`, but tell me if this fixes it or if you find some other error message (or maybe the same one).

**Comment by VinGarcia** [comment] 2024-10-25 01:04
@nenodias eu tentei reproduzir o erro que você tá tendo mas não consegui, qual banco de dados e adapter você está usando?

**Comment by nenodias** [comment] 2024-10-25 01:42
I'm using mysql with https://github.com/go-sql-driver/mysql

**Comment by VinGarcia** [comment] 2024-10-25 12:07
Here is an example of a minimum reproducible example:

https://gist.github.com/VinGarcia/4d75eeb277a4e6c087ee281ef3c2b9d5

I will try to adapt this to run on mysql maybe tomorrow, or maybe Sunday, if you can give me a minimum reproducible example before that I can probably figure out the issue sooner.

**Comment by nenodias** [comment] 2024-10-25 16:36
I created an example here.
https://gist.github.com/nenodias/01161556e4498d67242e9620c8317e8f

**Comment by VinGarcia** [comment] 2024-10-29 01:19
Hey @nenodias, nice thanks for the gist.

Ok I can reproduce it, and this allowed me to find a bug, I can fix it and I am already working on it, but maybe you don't have to wait for me to fix it:

If in your use-case it is possible to replace the type of the CnpjBasico field from `*string` to `string` that would make it work.

The bug I found is that I am not skipping the feature of retrieving IDs when the ID is not an auto-increment integer, so what happens is that  your query is entering a flow where KSQL thinks the ID is an integer and tries to update your struct ID field with the `.LastInsertID()` that comes from the database, which of course fails because `LastInsertID()` returns an integer and your field is a string.

I will try to get it fixed today, if I can't the fix I suggested above should work.

**Comment by VinGarcia** [comment] 2024-10-29 12:56
I actually was able to fix it yesterday, but the CI is broken for some reason, I will work on fixing it tonight.

**Comment by VinGarcia** [comment] 2024-10-30 12:34
Hey @nenodias, I just released a version with the fix for this problem.

Sometimes it takes some minutes or maybe a couple of hours for a new release version to be available, but you should soon be able to do a `go get -u github.com/vingarcia/ksql/adapters/kmysql` to get the latest version.

If you can test it and tell me if it is now working as expected I will close this issue.

One thing to note is that if you look at the landing page of this repo it now shows as if the coverage is 77%, this is not true, so don't worry about this version being less trustworthy than the previous one, it's just an issue with the CI.

**Comment by VinGarcia** [comment] 2024-10-30 12:35
Also thank you very much for reporting this issue and helping me reproduce it.

**Comment by VinGarcia** [comment] 2024-11-02 20:20
Hey @nenodias, I tested this issue again with the example you provided and it is indeed fixed now. So I will close this issue. Thanks again for reporting the error and helping me solve it. Feel free to open new issues in the future.

**Closed** 2024-11-04 01:33 UTC
