### ISSUE TITLE
Scanning DATE type into time.Time

### ISSUE THREAD

**Issue by giovanni-orciuolo** [VinGarcia/ksql#51] opened 2024-09-27 14:21 UTC
When I try to scan a field which is a column of type DATE (written in Postgres as 2024-09-27) I get the following error:

```
parsing time "2024-09-27" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "T"
```

Because ksql is trying to scan it as a DATETIME. Is there any way to make it scan as a PostgreSQL DATE (which has YYYY-MM-DD format)?

**Comment by VinGarcia** [comment] 2024-09-27 20:20
Hello @giovanni-orciuolo, I am actually traveling so I only have my cellphone right now, but I might still be able to help. 

So by default KSQL only forwards it's query arguments to the underlying database client, I am assuming you are using kpgx or kpgx5 as the backend adapter.

The only exception to this is if you are using a [modifier](https://github.com/VinGarcia/ksql/wiki/sql.Scan,-sql.Value-and-Modifiers#what-is-a-ksql-modifier), if you are using one of the `timeNowUtc*` modifiers they do expect the database column to be a DATETIME which would explain the error.

If this is the case there are several ways of working around this: 

1. If you don't really need to use a modifier you could just stop using it, maybe a default value of now() for this column would be enough.
2. If you do need it you could either change the database column type or create your own modifier (you can copy the original definitions of the `timeNow` modifier and change it)
3. It might be possible to submit a PR to make the existing modifier work with both types, but this one is more complex as it needs to work on postgres, SQLite, MySQL and sqlserver, and it also needs to be reasonably efficient

Tell me if this makes sense, I might be wrong in some of my assumptions

**Comment by VinGarcia** [comment] 2024-10-02 13:29
Hey @giovanni-orciuolo, I am back from my vacation, I just checked the code for the time modifiers and actually I don't think I am doing any custom parsing of date strings there:

https://github.com/VinGarcia/ksql/blob/master/internal/modifiers/time_modifiers.go

Which implies this is not handled by KSQL at all, it might be a different problem.

Can you get me some info on what database/driver you are working with and also an example of the table definition + the Go code with the query you are trying to run using KSQL?

**Comment by VinGarcia** [comment] 2024-10-04 20:09
Hmm, so this problem is probably not related to KSQL as we don't do anything with the query params, so I will close it for now. 

If you think this is indeed caused by KSQL feel free to create a new issue (or reopen this one, I am not sure if you would have the permissions for that though =P)

**Closed** 2024-10-07 01:17 UTC
